try {
    console.log(nome);
} catch (err) {
    console.log("Houve algum erro", err)
} finally {
    console.log("Boa noite");
}